server:
  port: 8004

spring:
  application:
    name: microservercloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mycloudDB01?characterEncoding=utf8&useSSL=true   # 数据库名称
    username: root
    password: 830925
    dbcp2:
      min-idle: 5               # 数据库连接池的最小连接数
      initial-size: 5           # 初始化连接数
      max-total: 5              # 最大连接数
      max-wait-millis: 200      # 等待连接获取的最大超时时间

# 整合mybatis
mybatis:
  configuration:
    cache-enabled: true # 开启二级缓存
#  config-location: classpath:mybatis/mybatis-config.xml   # mybatis配置文件，SpringBoot可以不用，全部配置在这里（如果在这里配置了，就不要再有mybatis的配置文件）
  type-aliases-package: com.dwx.springcloud.entities      # 与数据库表对应映射的JavaModel类
  mapper-locations: classpath:mybatis/mapper/**/*.xml     # 与持久化接口层实现xml文件位置

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservercloud-dept-hystrix-8004  # 自定义微服务名称
    prefer-ip-address: true # 显示IP地址

info:
  app.name: microservercloud-dept-hystrix-8004
  company.name: com.dwx.springcloud
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
